
Failures (2):
  JUnit Vintage:SortArray_143_1Test:testSortArrayWithDuplicateNumbers
    MethodSource [className = 'original.SortArray_143_1Test', methodName = 'testSortArrayWithDuplicateNumbers', methodParameterTypes = '']
    => java.lang.AssertionError: expected:<[2, 3, 3, 5, 5, 7, 9]> but was:<[2, 3, 3, 5, 5, 9, 7]>
       org.junit.Assert.fail(Assert.java:89)
       org.junit.Assert.failNotEquals(Assert.java:835)
       org.junit.Assert.assertEquals(Assert.java:120)
       org.junit.Assert.assertEquals(Assert.java:146)
       original.SortArray_143_1Test.testSortArrayWithDuplicateNumbers(SortArray_143_1Test.java:42)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:566)
       org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
       [...]
  JUnit Vintage:SortArray_143_1Test:testSortArray
    MethodSource [className = 'original.SortArray_143_1Test', methodName = 'testSortArray', methodParameterTypes = '']
    => java.lang.AssertionError: expected:<[2, 3, 5, 7, 9]> but was:<[2, 3, 5, 9, 7]>
       org.junit.Assert.fail(Assert.java:89)
       org.junit.Assert.failNotEquals(Assert.java:835)
       org.junit.Assert.assertEquals(Assert.java:120)
       org.junit.Assert.assertEquals(Assert.java:146)
       original.SortArray_143_1Test.testSortArray(SortArray_143_1Test.java:18)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:566)
       org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
       [...]

Test run finished after 51 ms
[         4 containers found      ]
[         0 containers skipped    ]
[         4 containers started    ]
[         0 containers aborted    ]
[         4 containers successful ]
[         0 containers failed     ]
[         4 tests found           ]
[         0 tests skipped         ]
[         4 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         2 tests failed          ]

